version: '3.7'

services:
  db:
    container_name: PostgreSQL
    image: docker.io/postgres:alpine
    restart: always
    volumes:
      - pgData:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: <YourStrong@Passw0rd>
      PGDATA: /var/lib/postgresql/data/pgdata 

volumes:
  pgData:
