Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/focal64"
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    jenkins.vm.network "private_network", ip: "192.168.56.10"

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    jenkins.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.cpus = "1"
    end
    jenkins.disksize.size = '50GB'

    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    jenkins.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
      apt-get update
      apt-get upgrade -y
      apt-get install nodejs -y
      apt-get install openjdk-17-jre-headless openjdk-17-jdk-headless -y
      apt-get install jenkins -y
    SHELL
  end

  config.vm.define "ftp_server" do |ftp_server|
    ftp_server.vm.box = "ubuntu/focal64"
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    ftp_server.vm.network "private_network", ip: "192.168.56.11"

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    ftp_server.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.cpus = "1"
    end
    ftp_server.disksize.size = '50GB'

    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    ftp_server.vm.provision "shell", inline: <<-SHELL
      apt-get update
      sudo apt-get -y install git build-essential tree curl
      sudo apt-get -y install vsftpd
    SHELL
  end
  
end


