Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/focal64"

    # using a specific IP.
    jenkins.vm.network "private_network", ip: "192.168.56.10"

    # Provider-specific configuration so you can fine-tune various
    jenkins.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.cpus = "1"
    end
    jenkins.disksize.size = '50GB'

    # Enable provisioning with a shell script. Additional provisioners 
    jenkins.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
      apt-get update
      apt-get upgrade -y
      apt-get install nodejs -y
      apt-get install openjdk-17-jre-headless openjdk-17-jdk-headless -y
      apt-get install jenkins -y
    SHELL
  end  
end


