version: "3.7"

services:
  db:
    container_name: MariaDB
    image: docker.io/mariadb:latest
    restart: always
    volumes:
      - mariaData:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: YourStrong@Passw0rd
      MARIADB_ROOT_HOST: \%

volumes:
  mariaData:
