apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        app: maria
    spec:
      containers:
        - name: maria
          image: docker.io/mariadb:latest
          ports:
            - containerPort: 3306
          env:
            # - name: MARIADB_ROOT_PASSWORD_HASH
            #   valueFrom:
            #     secretKeyRef:
            #       name: maria-secret
            #       key: maria-root-password
            - name: MARIADB_ROOT_HOST
              value: '%'
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: 'yes'
          volumeMounts:
            - name: maria-data
              mountPath: /var/lib/mysql
      volumes:
        - name: maria-data
          persistentVolumeClaim:
            claimName: maria-data-pvc

---
apiVersion: v1
kind: Secret
metadata:
  name: maria-secret
type: Opaque
data:
  maria-root-password: PFlvdXJTdHJvbmdAUGFzc3cwcmQ+Cg==

---
apiVersion: v1
kind: Service
metadata:
  name: maria-service
spec:
  selector:
    app: maria
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
