version: '3.7'

services:
  db:
    container_name: Mysql
    image: docker.io/mysql:latest
    restart: always
    volumes:
      - mysqlData:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: <YourStrong@Passw0rd>

volumes:
  mysqlData:
